apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drupal
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: tech.market
    http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: drupal-service
            port:
              number: 80
