apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drupal-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: tech.market
      http:
        paths:
          - path: /
            backend:
              serviceName: drupal-service
              servicePort: 80
