apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
type: Opaque
data:
    mysql-database: ZHJ1cGFsCg==
    mysql-root-password: cm9vdAo=
    mysql-username: ZHJ1cGFsCg==
    mysql-password: ZHJ1cGFsCg==
