apiVersion: v1
kind: Secret
metadata:
  name: my-registry-key
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIyMDI0OTMyNTQ5NzkuZGtyLmVjci5ldS13ZXN0LTIuYW1hem9uYXdz
LmNvbSI6IHsKCQkJImF1dGgiOiAiUVZkVE9tVjVTbmRaV0d4ellqSkdhMGxxYjJsYVJURXlWVVUw
ZVdSR1pFSlRSWFJ5WWtoR1FrNHhZM2xQVlZaM1lUSTFTbVJzWkdwbFJsRjRTekZrVkUxR2J6QlNi
SEJPVWxjeGJWVnFSbTFpYmxweVducFdiVTVJY0RCT01VSnRZVWM1UjFWclZUSk5NMnhyVGpKak1V
NHlUblZVVjNBeFZtc3hlbEp0WTNsVFJGb3lWRWRHU2xScVRtcFdWbGwzVGtkMFExUkdZM2xsYkc4
elN6RkZNbU5VYUVoWmFtaEpVMVV3ZVU5VWJGTlVWM0IyV1cwMWEyRXhXWGRPYTJ4M1RqTndWRmxy
UlhaV1YyeHJZV3RhTUU1NlNYZFVNblF4VXpOU2NsUnNVWGROUldSc1ZtcEtVMUl6Um5KV1JGcEZW
MWhTU21KNldrWmFSemsxWW1wQ1IwNVZVbXhPUlRWdVlVUk5NRlpHWTNkVU1VWTFXa2Q0VW1GdGFG
cGliWE15VlZSV1dsTlhiRnBWVkZsM1dWZHNhVTlZVG5SV1dFSk9UMFp3TVdWRVNqVmFNVzh5VWxW
ME5XRXdUa05aTTFrMVdWWlNUbHBZVG5Wa1JrNVdURE5DTlZwcVJrZE9iVXBxVDBWM05XVkVWak5r
UjA1MFUwZGtNVTlXY0U1WlZ6Vk1WMFZTV2xWR1ZrZE9NVmwyVlRBNVVsa3dUbTlqTTJ4NFZXdHpl
R0pIWkdoVFZVNXJTekJhYVZOdFZuZE1NSFIyWlVaR1RGTXlXWHBQUjAwd1VucEtNR1JHVmxOWGJr
WlVXVlJDUlZWNU9XdFdNVW93WVRKS1dsZHNWbTFhYTJSRlZGWnJORk5IYkZGV2JYQlNaVWhzVDFZ
eWNHcFNTR3hUVmpCV1lXRnFhRkpSV0ZKeFRERndRbE5FV205YVZrcExXa2RhUWxWdGRFbFNhbXQ2
VDFSU1FsVXhUbmhaV0VvMlZsZE9jMkV5TUhsalZVNXNWMVZPUzAxR1JsQlZhemt3WlVVeFdHSkdT
bE5OYm1Rd1V6RktWa3N5V21GV1JYQnhUREJzZW1GVmFFWlJiWEJwVTBSa1NXRldWazFXVlZaYVZF
WlJjbUZFUW1GWFZXeEVXbFJPZUZkV1dqRlRWVGxhVlVSV1UySnBPVXhVVlRRd1RVVnNUMU5WUmtK
YVNGWXdVV3RuTVdNeFVuZFhWWEJJV210U2EyVlliRzVqTVVwR1RXcGFORTVYTlV0UFJHeHVUa1pP
YVZkRWFHeFRSV2hSVERGbk1sTXdaM2xoTUhnd1ZqTmpORnBzVWpKalZ6azBZWHBOTTFGcVRuaGxi
bVExVjBSa1IxTnJiRU5rVjFwcVYxWndkMWxXVmpWUmJGSlhZVzVhTTFkRk5VdFJXR1JyWVhwb1Qy
SkdTbEpaVlZZelpXc3dlR050TVhkYVZVVXlaVVpSZW1Gc1pFZGhhMXB6VGpCS2VsVjVPRFZQVmxa
d1pHazVVMkZYVVhaaU1qRXlUVVpzZVU1R1dqTkxNbEpJWW14a01WWXdTbmhoYkVJelRsVldTMlJG
V1RKWmJXeDFZVzVDTlU0eU5UQmlia0Z5VFdwV1dXUXljSEJOZWtsM1RqRmplVmRJVmpGVFIwcEZV
MFZGTTAxVWJHNVNNVWwyV25rNGRrMUdXakJhTVZZeVZucHNVazFFVWxCamEwMXlXVEJTYldSWGJI
VlBWbHB3WTBjd2QxUXdTWEpTYWxad1N6TkZNRlZxYkdwWFJXUnJWbXhyZWtzeVVrbGlSelZvWkRC
c1YxWkZPVzFaTWpGd1ZVVnJlR0ZyYUhWV2Vsb3lZakF3Y2xSck1WcGphekZ3VERGR1JHTXdkSEJT
VlhNMFZHcE9UMVV4V2pCaE1rcFVZVVJTTUZWSVpFaFZiR1JKWkRGU1dHRXdhekZOZWxKd1kxUmFV
MVpZU2xkT1JFWlVUVVZLVUdWc1FtdFNSbEoxVFVSU2IxVlZNVXBoVld4UFZteFdUbEl4VFRSa1Ix
WXlUa1ZPVlZreVJqSlVNMW8yVld0amQxcEhlREpUTW5CM1dWaE9kRll3V1RST01uQjVWVzVWZGxV
emJGZFdSRVUwWWxkd2QySldaSGhaVkZseVRrZFdTVmR0V1hKTlZXaDFaVWhPYkUxc1dUUlZWR1F5
WVZWV1dHVkdRbkpNTVZKQ1ZEQlZNMkZZVmxCVVJrSmhZV2wwWVdSSFNtcFpNMnhSV1RCVmVHSlhS
bFprYkZKdVVtNWtZV1JZUWxKa1ZGcFJTekJHU0U5R1ZrTmtSWFJ6VG5wYWMyVnJhelJaYmxZd1RU
SkZNbHBzVGpWTk1Ga3haVmhTYjJOdFNtcGphMHA1V2tjMGVWZHFRbGRqTURsd1ZGWkdkRmt5YkZS
YVdFWkdWRzFSYVV4RFNtdFpXRkpvWVRKV05VbHFiMmxSVmtaR1VXdEdTV0ZGTlVWbGJHUlhZbXhz
U0dWWGVFeE5NMUpXV1ZkNFNWRlZOWGRpV0VwMVZWaHdhRTVZWXpCV2VsSnFVMFpzVGxaVVozbGtS
MHBQVTFoa1FsRlZSa2xPU0dSdFVWWnNTMU15T1dGVFYyZ3lXVEExUWxWWFRraGlNR00wWkRKS1Vs
TlZTa0pTUlVwMlVXMWtjbU5YYUhKaFZXTTFaSHBDUTFGdVpFWmtNR2h1VjFWd1dsTldjRXBSVm1S
V1VrVktRbEpZVms1UmExWkdVa1ZvYTA5R1JsZGxSbkJVWTFSSk0wNUdiSGhaTUVwdVUxVktSbE5W
UlROVVJYUXlaVmMxVUZkR1FteGlWbkJOWVdzME0xWnRiRmxaVlRWM1lURkNVbFZzUmxwa00zQkZZ
ekZXY0ZKV1pFOVhSVXBhWVd0T2IySnVXbEpYUlVwTlpGZE9SbFF4UmtsT2JuQjVUMVJXUWxONmJE
RlNSRnBWVjBkMFRHSkdaRTlOV0VKeFpEQjBUMUpVTUdsTVEwb3lXbGhLZW1GWE9YVkphbTlwVFds
SmMwbHVValZqUjFWcFQybEtSVkZXVWtKWU1IUkdWMU5KYzBsdFZqUmpSMng1V1ZoU2NHSXlOR2xQ
YWtVeVQwUkZORTlVVlRWTmFrSTUiCgkJfQoJfQp9

type: kubernetes.io/dockerconfigjson
